# Generated by Django 5.0.4 on 2024-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contact',
            new_name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('TN', 'Tehran'), ('KJ', 'Karaj'), ('GN', 'Gilan'), ('TZ', 'Tabriz'), ('MD', 'Mashhad')], default='TN', max_length=2),
        ),
    ]
