# Generated by Django 5.0.4 on 2024-04-19 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_contact_address_address_address_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default=123456, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.OneToOneField(default=12345, on_delete=django.db.models.deletion.PROTECT, to='home.code'),
            preserve_default=False,
        ),
    ]
