# Generated by Django 5.0.4 on 2024-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(default='custommer', max_length=120),
            preserve_default=False,
        ),
    ]
