# Generated by Django 5.0.4 on 2024-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('member', 'Member'), ('operator', 'Operator'), ('admin', 'Admin'), ('staff', 'Staff')], default='member', max_length=10),
        ),
    ]
